version: '3.8'

networks:
  infra_default:
    external: true  # connect to existing infra network created by infra/docker-compose.yml

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - infra_default

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana_monitoring
    user: "472"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    networks:
      - infra_default
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_monitoring
    pid: "host"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro
    ports:
      - "9100:9100"
    networks:
      - infra_default

#networks:
#  infra_default:
#    external: true