global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'milvus'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9091']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: 'node_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['node_exporter_monitoring:9100']

  - job_name: 'docker_containers'
    metrics_path: /metrics
    static_configs:
      # If you later add cAdvisor, change this target
      - targets: []

  - job_name: "fastapi"
    metrics_path: /prom_metrics
    static_configs:
      - targets: [ "host.docker.internal:8000" ]


# Alerting rules can be added here or in separate files
rule_files: []