global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus:9091']

  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']
